Feature/tests
YairFernando67/Tic-Tac-Toe-JS pull request #2
Opened 2020-04-23 18:00 UTC by YoseptF

We made the following test with jest:

- The gameController should
    -  ✓ be an object (3ms)
    - play with the selected square and
      - ✓ should fail if the square is already taken (16ms)
      - ✓ should succeed if the square is not already taken (4ms)
      - ✓ should win if you have 3 in a row (6ms)
      - ✓ should draw if nobody won (14ms)
    - start the game
      - ✓ display error message if players are null (2ms)
      - ✓ display player turn if players inputs are not null (2ms)

2020-04-23 20:42 UTC, maelfosso requested changes
# Changes required :red_circle: 

Hello @YoseptF @YairFernando67 
Everything is almost OK. 
Just a few thing to fix before moving forward.

Kindly read the comment left below and make the suggested changes then submit a new code review request.
Thanks

Mael FOSSO

2020-04-23 20:42 UTC, maelfosso commented on test/gameController.test.js
> +    });
The `win` method returns a boolean.
Write according to that not according the message. You except the win method to return either true or false.

2020-04-23 23:08 UTC, YoseptF commented
We added 2 more tests, now we are testing the `win` method, it returns false when someone won, and true if the game continues :D

2020-04-24 15:29 UTC, jofer86 approved these changes
## :wave: :wave: Hello!, I'm Jorge, and  I'm here to review this Pull Request, let's take a look shall we :eye: :eye: :eye: 
- Changes marked as **[OPTIONAL]** are not hard requirements but are nice to have.
- All the required changes were tackled!! Great job!!
# `STATUS: APPROVED` :rocket: :+1: :rocket: 
--------------------------------------------------------------------
Cheers, 
Jorge Fernando Rincón Figueroa.
Technical Support Engineer.
**Slack: @jofer86**

2020-04-24 17:10 UTC, merged